/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\astra.glb -T 
Files: .\astra.glb [20.26MB] > E:\Projects\React\FantaValorant-Client\public\models\astra-transformed.glb [1.82MB] (91%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function AstraModel(props: any) {
    const { scene } = useGLTF("/models/astra-transformed.glb") as any;
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone) as any;
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.563, 0]}>
                <skinnedMesh geometry={(nodes.Astra_1 as any).geometry} material={materials.Astra_Hair} skeleton={(nodes.Astra_1 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Astra_2 as any).geometry} material={materials.Astra_Arm} skeleton={(nodes.Astra_2 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Astra_3 as any).geometry} material={materials.Astra_Body} skeleton={(nodes.Astra_3 as any).skeleton} />
            </group>
        </group>
    );
}

useGLTF.preload("/models/astra-transformed.glb");
