/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\breach.glb -T 
Files: .\breach.glb [10.03MB] > E:\Projects\React\FantaValorant-Client\public\models\breach-transformed.glb [960.42KB] (90%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";

export function BreachModel(props: any) {
    const { scene } = useGLTF("/models/breach-transformed.glb") as any;
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);

    useEffect(() => {
        const mat = materials.Breach_Body as THREE.MeshStandardMaterial;
        const hair = materials.Breach_Hair as THREE.MeshStandardMaterial;

        mat.vertexColors = false;
        hair.vertexColors = false;

        mat.metalness = 0;
        hair.metalness = 0;

        mat.roughness = 0.8;
        hair.roughness = 0.8;
    }, [materials]);

    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.553, 0]}>
                <skinnedMesh
                    geometry={(nodes.Breach_Skelmeshmd as any).geometry}
                    material={materials.Breach_Hair}
                    skeleton={(nodes.Breach_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Breach_Skelmeshmd_1 as any).geometry}
                    material={materials.Breach_Body}
                    skeleton={(nodes.Breach_Skelmeshmd_1 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/breach-transformed.glb");
