/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\brimstone.glb -T 
Files: .\brimstone.glb [9MB] > E:\Projects\React\FantaValorant-Client\public\models\brimstone-transformed.glb [871.09KB] (90%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshStandardMaterial } from "three";

export function BrimstoneModel(props: any) {
    const { scene } = useGLTF("/models/brimstone-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);

    useEffect(() => {
        const body = materials.Brimstone_Body as MeshStandardMaterial;
        const eye = materials.Brimstone_Eye as MeshStandardMaterial;
        const stim = materials.Brimstone_StimPack as MeshStandardMaterial;

        body.vertexColors = false;
        //eye.vertexColors = false;
        stim.vertexColors = false;

        body.metalness = 0.3;
        eye.metalness = 0;
        stim.metalness = 0;
        

        body.roughness = 1;
        eye.roughness = 0.8;
        stim.roughness = 0.8;
    }, [materials]);

    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[Math.PI, -1.549, Math.PI]}>
                <skinnedMesh
                    geometry={(nodes.Brimstone_1 as any).geometry}
                    material={materials.Brimstone_StimPack}
                    skeleton={(nodes.Brimstone_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Brimstone_2 as any).geometry}
                    material={materials.Brimstone_Eye}
                    skeleton={(nodes.Brimstone_2 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Brimstone_3 as any).geometry}
                    material={materials.Brimstone_Body}
                    skeleton={(nodes.Brimstone_3 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/brimstone-transformed.glb");
