/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\chamber.glb -T 
Files: .\chamber.glb [10.97MB] > E:\Projects\React\FantaValorant-Client\public\models\chamber-transformed.glb [843.82KB] (92%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function ChamberModel(props: any) {
    const { scene } = useGLTF("/models/chamber-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);

    return (
        <group {...props} dispose={null} position={[0, -1, 0]} rotation={[0, -Math.PI / 2, 0]}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <skinnedMesh
                geometry={(nodes.Chamber_1 as any).geometry}
                material={materials.Chamber_body}
                skeleton={(nodes.Chamber_1 as any).skeleton}
            />
            <skinnedMesh
                geometry={(nodes.Chamber_2 as any).geometry}
                material={materials.Chamber_hair}
                skeleton={(nodes.Chamber_2 as any).skeleton}
            />
            <skinnedMesh
                geometry={(nodes.Chamber_3 as any).geometry}
                material={materials.Chamber_body}
                skeleton={(nodes.Chamber_3 as any).skeleton}
            />
        </group>
    );
}

useGLTF.preload("/models/chamber-transformed.glb");
