/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\cypher.glb -T 
Files: .\cypher.glb [7.97MB] > E:\Projects\React\FantaValorant-Client\public\models\cypher-transformed.glb [734.14KB] (91%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshStandardMaterial } from "three";

export function CypherModel(props: any) {
    const { scene } = useGLTF("/models/cypher-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const body = materials.Cypher as MeshStandardMaterial;

        body.vertexColors = false;

        body.metalness = 0.3;

        body.roughness = 1;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <skinnedMesh
                geometry={(nodes.Cypher_Skelmeshmo as any).geometry}
                material={materials.Cypher}
                skeleton={(nodes.Cypher_Skelmeshmo as any).skeleton}
                rotation={[0, -1.525, 0]}
            />
        </group>
    );
}

useGLTF.preload("/models/cypher-transformed.glb");
