/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\fade.glb -T 
Files: .\fade.glb [13.36MB] > E:\Projects\React\FantaValorant-Client\public\models\fade-transformed.glb [1.15MB] (91%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function FadeModel(props: any) {
    const { scene } = useGLTF("/models/fade-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh geometry={(nodes.Fade as any).geometry} material={materials.Fade_Body} skeleton={(nodes.Fade as any).skeleton} />
                <skinnedMesh geometry={(nodes.Fade_1 as any).geometry} material={materials.Fade_Hair} skeleton={(nodes.Fade_1 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Fade_2 as any).geometry} material={materials.Fade_Body} skeleton={(nodes.Fade_2 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Fade_3 as any).geometry} material={materials.Fade_Body} skeleton={(nodes.Fade_3 as any).skeleton} />
            </group>
        </group>
    );
}

useGLTF.preload("/models/fade-transformed.glb");
