/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\gekko.glb -T 
Files: .\gekko.glb [8.91MB] > E:\Projects\React\FantaValorant-Client\public\models\gekko-transformed.glb [802.05KB] (91%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function GekkoModel(props: any) {
    const { scene } = useGLTF("/models/gekko-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh geometry={(nodes.Gekko as any).geometry} material={materials.Gekko_Body} skeleton={(nodes.Gekko as any).skeleton} />
                <skinnedMesh geometry={(nodes.Gekko_1 as any).geometry} material={materials.Gekko_Body} skeleton={(nodes.Gekko_1 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Gekko_2 as any).geometry} material={materials.Gekko_Body} skeleton={(nodes.Gekko_2 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Gekko_3 as any).geometry} material={materials.Glass} skeleton={(nodes.Gekko_3 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Gekko_4 as any).geometry} material={materials.Gekko_Body} skeleton={(nodes.Gekko_4 as any).skeleton} />
            </group>
        </group>
    );
}

useGLTF.preload("/gekko-transformed.glb");
