/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\harbor.glb -T 
Files: .\harbor.glb [13.3MB] > E:\Projects\React\FantaValorant-Client\public\models\harbor-transformed.glb [1.16MB] (91%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function HarborModel(props: any) {
    const { scene } = useGLTF("/models/harbor-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh geometry={(nodes.Harbor as any).geometry} material={materials.Harbor_hair} skeleton={(nodes.Harbor as any).skeleton} />
                <skinnedMesh
                    geometry={(nodes.Harbor_1 as any).geometry}
                    material={materials.Harbor_Body}
                    skeleton={(nodes.Harbor_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Harbor_2 as any).geometry}
                    material={materials.Harbor_Body}
                    skeleton={(nodes.Harbor_2 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Harbor_3 as any).geometry}
                    material={materials.Harbor_Body}
                    skeleton={(nodes.Harbor_3 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Harbor_4 as any).geometry}
                    material={materials.Harbor_Body}
                    skeleton={(nodes.Harbor_4 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Harbor_5 as any).geometry}
                    material={materials.Harbor_Body}
                    skeleton={(nodes.Harbor_5 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/harbor-transformed.glb");
