/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\jett.glb -T 
Files: .\jett.glb [13.88MB] > E:\Projects\React\FantaValorant-Client\public\models\jett-transformed.glb [1.09MB] (92%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function JettModel(props: any) {
    const { scene } = useGLTF("/models/jett-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh geometry={(nodes.Jett as any).geometry} material={materials.Jett_body} skeleton={(nodes.Jett as any).skeleton} />
                <skinnedMesh geometry={(nodes.Jett_1 as any).geometry} material={materials.Jett_hair} skeleton={(nodes.Jett_1 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Jett_2 as any).geometry} material={materials.Jett_body} skeleton={(nodes.Jett_2 as any).skeleton} />
            </group>
        </group>
    );
}

useGLTF.preload("/models/jett-transformed.glb");
