/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\kayo.glb -T 
Files: .\kayo.glb [10.2MB] > E:\Projects\React\FantaValorant-Client\public\models\kayo-transformed.glb [1.03MB] (90%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function KayoModel(props: any) {
    const { scene } = useGLTF("/models/kayo-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh geometry={(nodes.Kayo as any).geometry} material={materials.Kayo_Body} skeleton={(nodes.Kayo as any).skeleton} />
                <skinnedMesh geometry={(nodes.Kayo_1 as any).geometry} material={materials.Kayo_Body} skeleton={(nodes.Kayo_1 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Kayo_2 as any).geometry} material={materials.Kayo_Body} skeleton={(nodes.Kayo_2 as any).skeleton} />
            </group>
        </group>
    );
}

useGLTF.preload("/models/kayo-transformed.glb");
