/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\killjoy.glb -T 
Files: .\killjoy.glb [13.4MB] > E:\Projects\React\FantaValorant-Client\public\models\killjoy-transformed.glb [1MB] (93%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function KilljoyModel(props: any) {
    const { scene } = useGLTF("/models/killjoy-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh
                    geometry={(nodes.Killjoy as any).geometry}
                    material={materials.KillJoy_Hair}
                    skeleton={(nodes.Killjoy as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Killjoy_1 as any).geometry}
                    material={materials.Killjoy_Glass}
                    skeleton={(nodes.Killjoy_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Killjoy_2 as any).geometry}
                    material={materials.Killjoy_Head}
                    skeleton={(nodes.Killjoy_2 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Killjoy_3 as any).geometry}
                    material={materials.Killjoy_Body}
                    skeleton={(nodes.Killjoy_3 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/killjoy-transformed.glb");
