/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\neon.glb -T 
Files: .\neon.glb [10.13MB] > E:\Projects\React\FantaValorant-Client\public\models\neon-transformed.glb [1.09MB] (89%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshStandardMaterial } from "three";

export function NeonModel(props: any) {
    const { scene } = useGLTF("/models/neon-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const body = materials.Neon_Body as MeshStandardMaterial;
        const hair = materials.Neon_Hair as MeshStandardMaterial;
        body.vertexColors = false;
        hair.vertexColors = false;
        body.metalness = 0.3;
        hair.metalness = 0.3;
        body.roughness = 1;
        hair.roughness = 1;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.571, 0]}>
                <skinnedMesh
                    geometry={(nodes.Neon_Skelmeshmd as any).geometry}
                    material={materials.Neon_Eye}
                    skeleton={(nodes.Neon_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Neon_Skelmeshmd_1 as any).geometry}
                    material={materials.Neon_Body}
                    skeleton={(nodes.Neon_Skelmeshmd_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Neon_Skelmeshmd_2 as any).geometry}
                    material={materials.Neon_Hair}
                    skeleton={(nodes.Neon_Skelmeshmd_2 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/neon-transformed.glb");
