/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\omen.glb -T 
Files: .\omen.glb [8.33MB] > E:\Projects\React\FantaValorant-Client\public\models\omen-transformed.glb [740.51KB] (91%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function OmenModel(props: any) {
    const { scene } = useGLTF("/models/omen-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);

    useEffect(() => {
        const body = materials.Omen_Body as MeshBasicMaterial;
        const head = materials.Omen_Head as MeshBasicMaterial;
        body.vertexColors = false;
        head.vertexColors = false;
    }, [materials]);

    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.547, 0]}>
                <skinnedMesh
                    geometry={(nodes.Omen_Skelmeshmd as any).geometry}
                    material={materials.Omen_Body}
                    skeleton={(nodes.Omen_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Omen_Skelmeshmd_1 as any).geometry}
                    material={materials.Omen_Head}
                    skeleton={(nodes.Omen_Skelmeshmd_1 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/omen-transformed.glb");
