/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\phoenix.glb -T 
Files: .\phoenix.glb [9.25MB] > E:\Projects\React\FantaValorant-Client\public\models\phoenix-transformed.glb [709.79KB] (92%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function PhoenixModel(props: any) {
    const { scene } = useGLTF("/models/phoenix-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const body = materials.Phoenix_Body as MeshBasicMaterial;
        const head = materials.Phoenix_Hair as MeshBasicMaterial;
        body.vertexColors = false;
        head.vertexColors = false;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.562, 0]}>
                <skinnedMesh
                    geometry={(nodes.Phoenix_Skelmeshmd as any).geometry}
                    material={materials.Phoenix_Body}
                    skeleton={(nodes.Phoenix_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Phoenix_Skelmeshmd_1 as any).geometry}
                    material={materials.Phoenix_Hair}
                    skeleton={(nodes.Phoenix_Skelmeshmd_1 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/phoenix-transformed.glb");
