/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\raze.glb -T 
Files: .\raze.glb [8.74MB] > E:\Projects\React\FantaValorant-Client\public\models\raze-transformed.glb [912.99KB] (90%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function RazeModel(props: any) {
    const { scene } = useGLTF("/models/raze-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const rocket = materials.Raze_RocketLauncher as MeshBasicMaterial;
        const body = materials.Raze_Body as MeshBasicMaterial;
        const granades = materials.Raze_Granades as MeshBasicMaterial;
        rocket.vertexColors = false;
        body.vertexColors = false;
        granades.vertexColors = false;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.528, 0]}>
                <skinnedMesh
                    geometry={(nodes.Raze_Skelmeshmd as any).geometry}
                    material={materials.Raze_RocketLauncher}
                    skeleton={(nodes.Raze_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Raze_Skelmeshmd_1 as any).geometry}
                    material={materials.Raze_Body}
                    skeleton={(nodes.Raze_Skelmeshmd_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Raze_Skelmeshmd_2 as any).geometry}
                    material={materials.Raze_Granades}
                    skeleton={(nodes.Raze_Skelmeshmd_2 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/raze-transformed.glb");
