/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\reyna.glb -T 
Files: .\reyna.glb [12.42MB] > E:\Projects\React\FantaValorant-Client\public\models\reyna-transformed.glb [971.7KB] (92%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function ReynaModel(props: any) {
    const { scene } = useGLTF("/models/reyna-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const eye = materials.Reyna_Eye as MeshBasicMaterial;
        const body = materials.Reyna_body as MeshBasicMaterial;
        const hair = materials.Reyna_Hair as MeshBasicMaterial;
        eye.vertexColors = false;
        body.vertexColors = false;
        hair.vertexColors = false;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Splitter} />
            <group rotation={[0, -Math.PI / 2, 0]}>
                <skinnedMesh geometry={(nodes.Reyna as any).geometry} material={materials.Reyna_Eye} skeleton={(nodes.Reyna as any).skeleton} />
                <skinnedMesh geometry={(nodes.Reyna_1 as any).geometry} material={materials.Reyna_body} skeleton={(nodes.Reyna_1 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Reyna_2 as any).geometry} material={materials.Reyna_Hair} skeleton={(nodes.Reyna_2 as any).skeleton} />
                <skinnedMesh geometry={(nodes.Reyna_3 as any).geometry} material={materials.Reyna_body} skeleton={(nodes.Reyna_3 as any).skeleton} />
            </group>
        </group>
    );
}

useGLTF.preload("/models/reyna-transformed.glb");
