/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\sage.glb -T 
Files: .\sage.glb [15.68MB] > E:\Projects\React\FantaValorant-Client\public\models\sage-transformed.glb [946.55KB] (94%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function SageModel(props: any) {
    const { scene } = useGLTF("/models/sage-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const body = materials.Sage_Body as MeshBasicMaterial;
        const orbs = materials.Sage_Orbs as MeshBasicMaterial;
        const hair = materials.Sage_Hair as MeshBasicMaterial;
        body.vertexColors = false;
        orbs.vertexColors = false;
        hair.vertexColors = false;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[Math.PI, -1.543, Math.PI]}>
                <skinnedMesh
                    geometry={(nodes.Sage_Skelmeshmd as any).geometry}
                    material={materials.Sage_Body}
                    skeleton={(nodes.Sage_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Sage_Skelmeshmd_1 as any).geometry}
                    material={materials.Sage_Orbs}
                    skeleton={(nodes.Sage_Skelmeshmd_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Sage_Skelmeshmd_2 as any).geometry}
                    material={materials.Sage_Hair}
                    skeleton={(nodes.Sage_Skelmeshmd_2 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/sage-transformed.glb");
