/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\skye.glb -T 
Files: .\skye.glb [10MB] > E:\Projects\React\FantaValorant-Client\public\models\skye-transformed.glb [914.18KB] (91%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function SkyeModel(props: any) {
    const { scene } = useGLTF("/models/skye-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const body = materials.Skye_Body as MeshBasicMaterial;
        const hair = materials.Skye_Hair as MeshBasicMaterial;

        body.vertexColors = false;
        hair.vertexColors = false;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.54, 0]}>
                <skinnedMesh
                    geometry={(nodes.Skye_Skelmeshmd as any).geometry}
                    material={materials.Skye_Body}
                    skeleton={(nodes.Skye_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Skye_Skelmeshmd_1 as any).geometry}
                    material={materials.Skye_Hair}
                    skeleton={(nodes.Skye_Skelmeshmd_1 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/skye-transformed.glb");
