/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\sova.glb -T 
Files: .\sova.glb [14.43MB] > E:\Projects\React\FantaValorant-Client\public\models\sova-transformed.glb [1.23MB] (92%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function SovaModel(props: any) {
    const { scene } = useGLTF("/models/sova-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);

    useEffect(() => {
        const arrow = materials.Sova_Arrow as MeshBasicMaterial;
        const body = materials.Sova_Body as MeshBasicMaterial;
        const bow = materials.Sova_Bow as MeshBasicMaterial;
        const gauntlet = materials.Sova_Gauntlet as MeshBasicMaterial;
        const hair = materials.Sova_Hair as MeshBasicMaterial;

        arrow.vertexColors = false;
        bow.vertexColors = false;
        gauntlet.vertexColors = false;
        body.vertexColors = false;
        hair.vertexColors = false;
    }, [materials]);

    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.524, 0]}>
                <skinnedMesh
                    geometry={(nodes.Sova_Skelmeshmd as any).geometry}
                    material={materials.Sova_Arrow}
                    skeleton={(nodes.Sova_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Sova_Skelmeshmd_1 as any).geometry}
                    material={materials.Sova_Body}
                    skeleton={(nodes.Sova_Skelmeshmd_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Sova_Skelmeshmd_2 as any).geometry}
                    material={materials.Sova_Bow}
                    skeleton={(nodes.Sova_Skelmeshmd_2 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Sova_Skelmeshmd_3 as any).geometry}
                    material={materials.Sova_Gauntlet}
                    skeleton={(nodes.Sova_Skelmeshmd_3 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Sova_Skelmeshmd_4 as any).geometry}
                    material={materials.Sova_Hair}
                    skeleton={(nodes.Sova_Skelmeshmd_4 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/sova-transformed.glb");
