/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\viper.glb -T 
Files: .\viper.glb [9.49MB] > E:\Projects\React\FantaValorant-Client\public\models\viper-transformed.glb [990.06KB] (90%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function ViperModel(props: any) {
    const { scene } = useGLTF("/models/viper-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[0, -1.526, 0]}>
                <skinnedMesh
                    geometry={(nodes.Viper_Skelmeshmd019 as any).geometry}
                    material={materials.Viper_Eye}
                    skeleton={(nodes.Viper_Skelmeshmd019 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Viper_Skelmeshmd019_1 as any).geometry}
                    material={materials.Viper_Hair}
                    skeleton={(nodes.Viper_Skelmeshmd019_1 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Viper_Skelmeshmd019_2 as any).geometry}
                    material={materials.Viper_Body}
                    skeleton={(nodes.Viper_Skelmeshmd019_2 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Viper_Skelmeshmd019_3 as any).geometry}
                    material={materials.Viper_Props}
                    skeleton={(nodes.Viper_Skelmeshmd019_3 as any).skeleton}
                />
            </group>
            <group rotation={[0, -1.526, 0]}>
                <skinnedMesh
                    geometry={(nodes.Viper_Skelmeshmd023 as any).geometry}
                    material={materials.Viper_Hair}
                    skeleton={(nodes.Viper_Skelmeshmd023 as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Viper_Skelmeshmd023_1 as any).geometry}
                    material={materials.Viper_Body}
                    skeleton={(nodes.Viper_Skelmeshmd023_1 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/viper-transformed.glb");
