/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\yoru.glb -T 
Files: .\yoru.glb [9.8MB] > E:\Projects\React\FantaValorant-Client\public\models\yoru-transformed.glb [806.28KB] (92%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import type { MeshBasicMaterial } from "three";

export function YoruModel(props: any) {
    const { scene } = useGLTF("/models/yoru-transformed.glb");
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
    const { nodes, materials } = useGraph(clone);
    useEffect(() => {
        const body = materials.Yoru_Body as MeshBasicMaterial;
        const hair = materials.Yoru_Hair as MeshBasicMaterial;
        body.vertexColors = false;
        hair.vertexColors = false;
    }, [materials]);
    return (
        <group {...props} dispose={null}>
            <primitive object={nodes.Spine1} />
            <primitive object={nodes.Pelvis} />
            <group rotation={[Math.PI, -1.558, Math.PI]}>
                <skinnedMesh
                    geometry={(nodes.Yoru_Skelmeshmd as any).geometry}
                    material={materials.Yoru_Body}
                    skeleton={(nodes.Yoru_Skelmeshmd as any).skeleton}
                />
                <skinnedMesh
                    geometry={(nodes.Yoru_Skelmeshmd_1 as any).geometry}
                    material={materials.Yoru_Hair}
                    skeleton={(nodes.Yoru_Skelmeshmd_1 as any).skeleton}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/models/yoru-transformed.glb");
